---
- name: Configure Apache HTTP and HTTPS for slimme-rik.sasm.uclllabs.be
  hosts: all
  become: yes

  vars:
    default_web_dir: /var/www/html/default
    www1_web_dir: /var/www/html/www1
    www2_web_dir: /var/www/html/www2
    private_dir: /var/www/html/www1/private
    htpasswd_file: /etc/apache2/.htpasswd
    htpasswd_user: check
    htpasswd_password: ch3ck


  tasks:
    - name: Install Apache and required packages
      apt:
        name:
          - apache2
          - libapache2-mod-php
          - certbot
          - python3-certbot-apache
        state: present

    - name: Enable Apache modules
      command: a2enmod {{ item }}
      with_items:
        - ssl
        - rewrite
        - headers
        - auth_basic

    - name: Ensure Apache is running
      service:
        name: apache2
        state: started
        enabled: true


    - name: Create default webpage directory
      file:
        path: "{{ default_web_dir }}"
        state: directory
        owner: www-data
        group: www-data

    - name: Create default index.html
      copy:
        dest: "{{ default_web_dir }}/index.html"
        content: "<html><body><h1>welcome nicolas-benedettigonzalez.sasm.uclllabs.be</h1></body></html>"
        owner: www-data
        group: www-data

    - name: Configure default vhost
      copy:
        dest: /etc/apache2/sites-available/000-default.conf
        content: |
          <VirtualHost *:80>
                  ServerName www.nicolas-benedettigonzalez.sasm.uclllabs.be
                  ServerAlias default.nicolas-benedettigonzalez.sasm.uclllabs.be

                  ServerAdmin webmaster@localhost
                  DocumentRoot /var/www/html/default

                  ErrorLog /var/log/apache2/default_error.log
                  CustomLog /var/log/apache2/default_access.log combined

                  <Directory /var/www/html/default>
                            AllowOverride All
                            Require all granted
                  </Directory>

                  DirectoryIndex index.html

          </VirtualHost>
      notify: Restart Apache


    - name: Create www1 webpage
      file:
        path: "{{ www1_web_dir }}"
        state: directory
        owner: www-data
        group: www-data

    - name: Create www1 index.html
      copy:
        dest: "{{ www1_web_dir }}/index.html"
        content: "<html><body><h1>www1</h1></body></html>"
        owner: www-data
        group: www-data

    - name: Create www2 webpage
      file:
        path: "{{ www2_web_dir }}"
        state: directory
        owner: www-data
        group: www-data

    - name: Create www2 toupper.php
      copy:
        dest: "{{ www2_web_dir }}/toupper.php"
        content: |
          <?php
          if (isset($_GET['code'])) {
              echo strtoupper($_GET['code']);
          }
          ?>
        owner: www-data
        group: www-data

    - name: Configure www1 vhost
      copy:
        dest: /etc/apache2/sites-available/www1.conf
        content: |
          <VirtualHost *:80>
              ServerName www1.nicolas-benedettigonzalez.sasm.uclllabs.be
              ServerAlias www1
              DocumentRoot /var/www/html/www1
              ErrorLog /var/log/apache2/www1_error.log
              CustomLog /var/log/apache2/www1_access.log combined
              <Directory /var/www/html/www1>
                  AllowOverride None
                  Require all granted
                  DirectoryIndex index.html
              </Directory>

              <Directory /var/www/html/www1/private>
                  AllowOverride AuthConfig
                  Require all granted
                  DirectoryIndex index.html
              </Directory>
              </VirtualHost>

      notify: Reload Apache

    - name: Configure www2 vhost
      copy:
        dest: /etc/apache2/sites-available/www2.conf
        content: |
          <VirtualHost *:80>
              ServerName www2.nicolas-benedettigonzalez.sasm.uclllabs.be
              DocumentRoot /var/www/html/www2

              ErrorLog ${APACHE_LOG_DIR}/www2_error.log
              CustomLog ${APACHE_LOG_DIR}/www2_access.log combined

              <Directory /var/www/html/www2>
                  AllowOverride None
                  Require all granted
              </Directory>

              DirectoryIndex toupper.php
          </VirtualHost>
      notify: Reload Apache

    - name: Enable www1 and www2 vhosts
      command: a2ensite {{ item }}
      with_items:
        - www1.conf
        - www2.conf


    - name: Create private directory
      file:
        path: "{{ private_dir }}"
        state: directory
        owner: www-data
        group: www-data

    - name: Configure secure vhost
      copy:
        dest: /etc/apache2/sites-available/secure.conf
        content: |
          <VirtualHost *:80>
              ServerName secure.nicolas-benedettigonzalez.sasm.uclllabs.be
              Redirect permanent / https://secure.nicolas-benedettigonzalez.sasm.uclllabs.be/
          </VirtualHost>

          <VirtualHost *:443>
              ServerName secure.nicolas-benedettigonzalez.sasm.uclllabs.be
              DocumentRoot /var/www/html/secure

              SSLEngine on

              SSLCertificateFile /root/.acme.sh/nicolas-benedettigonzalez.sasm.uclllabs.be_ecc/fullchain.cer
              SSLCertificateKeyFile /root/.acme.sh/nicolas-benedettigonzalez.sasm.uclllabs.be_ecc/nicolas-benedettigonzalez.sasm.uclllabs.be.key

              <Directory /var/www/html/secure>
                  AllowOverride All
              </Directory>
          </VirtualHost>
      notify: Reload Apache

    - name: Configure supersecure vhost
      copy:
        dest: /etc/apache2/sites-available/supersecure.conf
        content: |
          <VirtualHost *:80>
              ServerName supersecure.nicolas-benedettigonzalez.sasm.uclllabs.be
              Redirect permanent / https://supersecure.nicolas-benedettigonzalez.sasm.uclllabs.be/
          </VirtualHost>

          <VirtualHost *:443>
              ServerName supersecure.nicolas-benedettigonzalez.sasm.uclllabs.be
              DocumentRoot /var/www/html/supersecure

              SSLEngine on
              SSLCertificateFile /root/.acme.sh/nicolas-benedettigonzalez.sasm.uclllabs.be_ecc/fullchain.cer
              SSLCertificateKeyFile /root/.acme.sh/nicolas-benedettigonzalez.sasm.uclllabs.be_ecc/nicolas-benedettigonzalez.sasm.uclllabs.be.key

              Header always set Strict-Transport-Security "max-age=31536000; includeSubDomains"

              <Directory /var/www/html/supersecure>
                  AllowOverride All
              </Directory>
          </VirtualHost>
      notify: Reload Apache

    - name: Enable HTTPS vhosts
      command: a2ensite {{ item }}
      with_items:
        - secure.conf
        - supersecure.conf

  handlers:
    - name: Reload Apache
      service:
        name: apache2
        state: reloaded

    - name: Restart Apache
      service:
        name: apache2
        state: restarted
