#!/bin/bash

# Find zone files older than 4 hours and delete
find /var/lib/bind/yoda_zone_*.db -type f -mmin +240 | while read -r ZONE_FILE; do
  ZONE_NAME=$(basename "$ZONE_FILE" .db | sed 's/^yoda_zone_//')
  
  # Remove zone configuration in named.conf.yoda-zones
  sed -i "/zone \"$ZONE_NAME.nicolas-benedettigonzalez.sasm.uclllabs.be\"/,+3d" /etc/bind/named.conf.yoda-zones

  # Remove NS record in primary zone
  sed -i "/$ZONE_NAME.nicolas-benedettigonzalez.sasm.uclllabs.be/d" /var/lib/bind/nicolas-benedettigonzalez.sasm.uclllabs.be.db

  # Delete the zone file
  rm -f "$ZONE_FILE"
  echo "Removed zone: $ZONE_NAME"
done

# Reload BIND
systemctl reload bind9
