#!/bin/bash
# Is the eth0 interface up? If not, wait.
while ! ip link show eth0 | grep -q "state UP"; do
    sleep 1
done
# Add the static arp entry (very sigma)
arp -s 193.191.176.254 ca:fe:c0:ff:ee:00 -i eth0
